name: Тестирование Coveralls

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v2

    - name: Установка Maven
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Сборка проекта
      run: mvn clean install

    - name: Генерация Jacoco отчетов
      run: mvn jacoco:report

    - name: Отправка отчета на Coveralls
      uses: coverallsapp/github-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-coverage: target/site/jacoco/jacoco.xml